name: CI

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npx oxfmt --check .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 25]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm cit

  docker-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 25]
    steps:
      - uses: actions/checkout@v6
      - run: docker build -f test.Dockerfile -t serve-test:${{ matrix.node-version }} --build-arg NODE_VERSION=${{ matrix.node-version }} .
      - run: docker run --rm serve-test:${{ matrix.node-version }}
